### ISSUE TITLE
errors when I active cherry-sidebar-manager-master

### ISSUE THREAD

**Issue by aalsubaey** [CherryFramework/cherry-sidebar-manager#2]
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/www/fitnesssweet.qa/wp-content/plugins/cherry-sidebar-manager-master/cherry-framework/modules/cherry-ui-elements/cherry-ui-elements.php on line 127

**Comment by ghost** [comment]
@aalsubaey hello, and thanks for your feedback!

We're working on the issue right now.

Currently you can fix this issue by opening the `/home/www/fitnesssweet.qa/wp-content/plugins/cherry-sidebar-manager-master/cherry-framework/modules/cherry-ui-elements/cherry-ui-elements.php` file and **on line 127** you will find following code:

``` php
$ui_class_name::enqueue_assets();
```

Just replace it with the snippet bellow:

``` php
call_user_func( array( $ui_class_name, 'enqueue_assets' ) );
```

**Comment by aalsubaey** [comment]
Hi

Is it solved ?

**Comment by aalsubaey** [comment]
Sorry I didn't read the previous email , thanks for your support
